### ISSUE TITLE
Tolong tambahkan kolom bayar dan sisa di tabel hot_payment dengan perintah ini.

### ISSUE THREAD

**Issue by MubarokMuhammad** [prismaposaddkomputer/prisma-pos#48]
ALTER TABLE hot_payment
ADD COLUMN IF NOT EXISTS
bayar int(155) after grand_total;

ALTER TABLE hot_payment
ADD COLUMN IF NOT EXISTS
sisa int(155) after bayar;

**Comment by chrisnabayuaji** [comment]
On process
